---
general:
  host: "localhost"
  port: 9999
  log_level: "debug"
  frame_source:
    type: "oakd_device"
    parameters:
      ip: "192.168.10.14"
      deviceid: 3
      stream_color_video: True
      stream_depth_video: True
      stream_body: True
      streaming_color_format: "COLOR_BGRA32"
      streaming_color_resolution: "COLOR_RESOLUTION_720P"
      streaming_depth_mode: "STEREO_DISPARITY"
      streaming_depth_resolution: "STEREO_RESOLUTION_480P"
      streaming_rate: "30"
      model: "@{REL}/models/human-pose-estimation-3d-0001.xml"
video_encoder:
  0: #color
    type: "null"
  1: #depth
    type: "null"
  4: #object-human
    type: "null"